# Generated by Django 3.2.5 on 2021-07-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'garagem',
                'ordering': ['descricao'],
            },
        ),
    ]
