# Generated by Django 3.2.5 on 2021-07-04 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20210703_2331'),
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='pessoa',
            field=models.ForeignKey(db_column='pessoa', null=True, on_delete=django.db.models.deletion.CASCADE, to='pessoa.pessoa'),
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('cor', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('tipo', models.IntegerField(choices=[(1, 'Carro'), (1, 'Moto')], default=1)),
                ('garagem', models.ManyToManyField(to='garagem.Garagem')),
            ],
            options={
                'db_table': 'veiculo',
                'ordering': ['descricao'],
            },
        ),
    ]
