# Generated by Django 3.2.5 on 2021-07-05 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_alter_pessoa_email'),
        ('garagem', '0002_auto_20210704_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagem',
            name='pessoa',
            field=models.ForeignKey(db_column='pessoa', on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='pessoa.pessoa'),
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='garagem',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='garagem',
            field=models.ForeignKey(db_column='garagem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garagem', to='garagem.garagem'),
        ),
    ]
