# Generated by Django 3.2.5 on 2021-07-05 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_auto_20210704_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='garagem',
            field=models.ForeignKey(db_column='garagem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='garagem.garagem'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Carro'), (2, 'Moto')]),
        ),
    ]
