# Generated by Django 3.2.5 on 2021-07-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pessoa',
                'ordering': ['nome'],
            },
        ),
    ]
