# Generated by Django 3.2.5 on 2021-07-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Administrador'), (1, 'Consumidor')], default=1),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
